fix: delete already closed client on closeSameClients
moscajs/aedes pull request #929
Opened 2024-01-08 17:02 UTC by Gianluca-Casagrande-Stiga

2024-01-08 17:04 UTC, Gianluca-Casagrande-Stiga commented
This should resolve https://github.com/moscajs/aedes/issues/928, but I would like to add a related test

2024-01-08 17:09 UTC, robertsLando requested changes

2024-01-08 17:09 UTC, robertsLando commented on package.json
> +  "version": "0.50.2",
Do not bump version please, It's automatically done on release

2024-01-09 08:45 UTC, robertsLando requested changes
Test?

2024-01-12 14:57 UTC, robertsLando approved these changes

2024-01-12 14:58 UTC, merged